### ISSUE TITLE
Ability to keep the Finishes and default group

### ISSUE THREAD

**Issue by LonelyDaoist** [Loupimo/UniversalSwatchSlots#1]
Hello, 
Currently when setting up a palette, it will replace all the swatches. Is it possible to keep the finishes (chrome, copper, carbon, caterium) and the default group (FICSIT Factory swatch, Project Assembly swatch, FICSIT Foundation swatch, pipeline swatch) ?

Cheers

**Comment by Loupimo** [comment]
Hello,
This is strange, the mod is design to not overwrite these slots. Could you please provide me more information like (if possible grouped in a zip file):
- The log file (C:\Users\YourUserName\AppData\Local\FactoryGame\Saved\Logs\FactoryGame.log) after you loaded your game.
- If possible, your save game.
- Are you playing on singleplayer, Host/Client (then were you the host our the client ?), dedicated server (Windows / Linux) ?
- The list of mod you have installed
- Your JSON configuration file ("YourStatifactoryGameFolder/FactoryGame/Configs/UniversalSwatchSlots.cfg")

If you have more than 255 swatches (includind default, finishes and custom) that might be the reason (I haven't checked if there was a limit...

Thank you !

**Comment by LonelyDaoist** [comment]
Hey, It was my mistake, I didn't look to the menu on the left to see the colors tab, I thought it just replaced all the swatches

really sorry for the false alarm
